name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    name: Compile resume pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            xelatex yanzhi_zhang_cv_en.tex
            xelatex yanzhi_zhang_cv_cn.tex
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply xelatex changes
